# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b55677e075b8eced947952a9350822339ab080782dd59ffb929f12d65ba39b452488955065835f13b5f3315f297298164368754abed2090cdb53bc9f5c4a8f7

test:
  secret_key_base: 74ee46d6bb2481e8f7b179ae92255f71a64d5714e5f928ac82e41cc75a7d86b7249b274092a8df5c37f21f8e884b67008478e9935a75f8f1d0a217e5c56ab51a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
